// Embeds the app icon, version info and manifest (asInvoker, per-monitor DPI) into the exe.
fn main() {
    println!("cargo:rerun-if-changed=assets/app.ico");
    println!("cargo:rerun-if-changed=assets/app.manifest");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    let mut res = winresource::WindowsResource::new();
    // The icon is generated by `cargo run --example gen_assets`; tolerate its absence
    // so that command can bootstrap itself.
    if std::path::Path::new("assets/app.ico").exists() {
        res.set_icon("assets/app.ico");
    }
    res.set_manifest_file("assets/app.manifest");
    res.set("ProductName", "Network Monitor");
    res.set("FileDescription", "Network Monitor");
    res.set("LegalCopyright", "Copyright (c) Network Monitor contributors");
    if let Err(e) = res.compile() {
        panic!("failed to embed Windows resources: {e}");
    }
}
